^[Query hasFatherInLaw]
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a1: <http://www.co-ode.org/roberts/family-tree.owl#>
SELECT DISTINCT ?X ?Y
WHERE
{ ?X a1:hasFatherInLaw ?Y }